USE INFOADB;

CREATE TABLE TB_AGENDA(
ID_AGENDA 		INT PRIMARY KEY AUTO_INCREMENT,
NM_CONTATO		VARCHAR(200),
DS_TELEFONE		VARCHAR(200),
DS_EMAIL		VARCHAR(200),
BT_FAVORITO		BOOLEAN,
DT_CADASTRO		DATETIME
);