
--INSERIR UM CONTATO
INSERT INTO TB_AGENDA(NM_CONTATO, DS_TELEFONE, DS_EMAIL, BT_FAVORITO, DT_CADASTRO)
		VALUES (?, ?, ?, ?, ?);

--SELECIONAR TODOS OS CONTATOS
SELECT * FROM TB_AGENDA;

--SELECIONAR ALGUM CONTATO PELO NOME
SELECT * FROM TB_AGENDA
WHERE NM_CONTATO LIKE '%?%';

--SELECIONAR OS CONTATOS FAVORITOS
SELECT * FROM TB_AGENDA
WHERE BT_FAVORITO = 1;

--SELECIONE OS CONTATOS CADASTRADOS EM UM PERÍODO DE TEMPO
SELECT * FROM TB_AGENDA
WHERE DT_CADASTRO BETWEEN ? AND ?;

--ALTERAR UM CONTATO
UPDATE TB_AGENDA
SET NM_CONTATO = ?,
	DS_TELEFONE = ?,
    DS_EMAIL = ?
    BT_FAVORITO = ?,
    DT_CADASTRO = ?
WHERE ID_AGENDA = ?;

--APAGAR UM CONTATO
DELETE FROM TB_AGENDA
WHERE ID_AGENDA = ?;